# Generated by Selenium IDE
import pytest
import time
import json
from selenium.webdriver.chrome.options import Options#chrome  
from selenium import webdriver
from selenium.webdriver.common.by import By
# from selenium.webdriver.firefox.options import Options # firefox
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


##chrome
chrome_options = Options()  
chrome_options.add_argument("--headless")
driver = webdriver.Chrome(chrome_options=chrome_options)

##Firefox
# options = Options()
# options.headless = True
# driver = webdriver.Firefox(options=options)
dish=input('ENTER DISH NAME: ')
driver.get("https://www.bestindiancooking.com")

# time.sleep(2)
WebDriverWait(driver,30).until(lambda driver: driver.find_element_by_name('s'))
driver.find_element(By.NAME, "s").click()
driver.find_element(By.NAME, "s").send_keys(dish)
driver.find_element(By.NAME, "s").send_keys(Keys.ENTER)

WebDriverWait(driver,30).until(lambda driver: driver.find_elements_by_xpath('//h3[@class="title-3"]'))

time.sleep(3)
title=driver.find_elements_by_xpath('//h2[@class="title-2"]')

WebDriverWait(driver,30).until(lambda driver: driver.find_elements_by_xpath('//div[@class="excerpt"]'))
ingredients=driver.find_elements_by_xpath('//div[@class="excerpt"]')

food={}
for i,j in enumerate(title):
  if(i<10):
    dish_name=j.text
    j=driver.find_element_by_partial_link_text(dish_name[:len(dish_name)//2])
    dish_link=(j.get_attribute('href')) 
    dish_ingr=ingredients[i].text
    print(dish_name)
    print(dish_link)
    print(dish_ingr)
    print()




